language: java
jdk: openjdk13

# install:
#   - mettre une commmande si nécessaire

script:
  - cd lab1
  - mvn package

os:
  - linux
  - osx

matrix:
  include:
  - name: "5.5.2 JUnit5"
    java: "openjdk13"
    env: TEST_SUITE=suite_3_5_unit
script: ./test.py $TEST_SUITE
