language: java
jdk: openjdk13

# install:
#   - mettre une commmande si nécessaire

os:
  - linux
  - osx

matrix:
  include:
  - name: "5.5.2 JUnit5"
    java: "openjdk13"

script:
  - cd lab1
  - mvn package
